export const CHANGE_DJ_RADIO_CATEGORIES = "djRadio/CHANGE_DJ_RADIO_CATEGORIES";

export const CHANGE_DJ_RADIO_PROGRAM_RECOMMEND_LIST = "djRadio/CHANGE_DJ_RADIO_PROGRAM_RECOMMEND_LIST";
export const CHANGE_DJ_RADIO_PROGRAM_RANK_LIST = "djRadio/CHANGE_DJ_RADIO_PROGRAM_RANK_LIST";

export const CHANGE_CATE_RECOMMEND_LIST = "dRadio/CHANGE_CATE_RECOMMEND_LIST"
